# Generated by Django 4.2.11 on 2024-04-25 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passager_reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservationhub.client'),
        ),
    ]
