# Generated by Django 4.2.11 on 2024-04-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0002_reservation_passager_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationhub.passager'),
        ),
    ]
