# Generated by Django 4.2.11 on 2024-04-25 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservationhub', '0004_rename_utilisateur_reservation_utilisateur_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager',
            name='utilisateur_associe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
