# Generated by Django 4.2.11 on 2024-04-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0005_passager_utilisateur_associe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passager',
            old_name='utilisateur_associe',
            new_name='utilisateur',
        ),
    ]
