# Generated by Django 4.2.11 on 2024-04-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0006_rename_utilisateur_associe_passager_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passager_reservation',
        ),
    ]
