# Generated by Django 4.2 on 2024-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0007_remove_reservation_passager_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gare',
            name='latitude',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gare',
            name='longitude',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
