# Generated by Django 4.2.11 on 2024-04-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0007_remove_reservation_passager_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_attente', models.DurationField()),
                ('trajet_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_arrivee', to='reservationhub.trajet')),
                ('trajet_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_depart', to='reservationhub.trajet')),
            ],
        ),
    ]
