# Generated by Django 4.2.11 on 2024-05-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0008_correspondance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correspondance',
        ),
    ]
