# Generated by Django 4.2 on 2024-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0008_gare_latitude_gare_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gare',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='gare',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
