# Generated by Django 4.2.11 on 2024-05-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationhub', '0009_delete_correspondance'),
        ('reservationhub', '0010_alter_gare_latitude_alter_gare_longitude'),
    ]

    operations = [
    ]
